library(KoNLP)
library(RColorBrewer)
useNIADic()
setwd("~/R_test/ch_09")
speech <- readLines("./data/ch9_speech_kor.txt")
noun1 <- extractNoun(speech)
noun2 <- unlist(noun1)
noun3 <- noun2[nchar(noun2) >= 2 ]
nounCount1 <- table(noun3)
nounCount <- head(sort(nounCount1,decreasing=TRUE),20)
print(nounCount)